/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uts;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class home extends javax.swing.JFrame {

    private static home instance;
    private boolean isLoggedIn = false;
    private JLabel lblBarang, lblLaporan;
    private JMenuItem menuItemLogin;

    private String username;
    private String role;

    // Tambahkan variabel baru untuk menyimpan status menu
    private boolean menuUserEnabled = false;

    /**
     * Creates new form menuUtama
     */
    public home(String username, String role) {
        this.username = username;
        this.role = role;
        initComponents(); 
        
        // Periksa apakah username dan role null atau kosong
        if (username == null || username.isEmpty() || role == null || role.isEmpty()) {
            lblUsername.setVisible(false); // Sembunyikan lblUsername jika username dan role kosong
        } else {
            lblUsername.setText("Selamat Datang, " + username + " sebagai " + role);
        }
        
        setMenuEnabled(true, role); 
}


public void enableAllMenus() {
    // Contoh: aktifkan semua menu, tombol, atau fungsi yang perlu diaktifkan
    jMenu1.setEnabled(true);
    jMenu2.setEnabled(true);
    jMenu4.setEnabled(true);
    jMenu5.setEnabled(true);
    jMenuItem1.setEnabled(true); 
    jMenuItem2.setEnabled(true);
    mnLogin.setVisible(false);  // Sembunyikan sub-menu login  
    if (role.equalsIgnoreCase("admin")) {
        jMenuItem1.setVisible(true); // Tampilkan 'Manage User' untuk admin
        jMenuItem2.setEnabled(true);
    } else if (role.equalsIgnoreCase("kasir")) {
        jMenuItem1.setVisible(false); // Sembunyikan 'Manage User' untuk kasir
        jMenuItem2.setEnabled(true);
    }
  
}
 public static home getInstance(String username, String role) {
        if (instance == null) {
            instance = new home(username, role);
        } else {
            instance.username = username; // Update username
            instance.role = role; // Update role
            instance.lblUsername.setText("Selamat Datang, " + username + " sebagai " + role); // Update label
        }
        return instance;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnLogin = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        transaksi = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(54, 48, 98));
        jPanel1.setForeground(new java.awt.Color(54, 48, 98));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("TOKO RAMAYANI");

        jLabel2.setText("Jl. Kenangan No. 10 Madiun");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsername)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsername)
                .addContainerGap(412, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uts/User.png"))); // NOI18N
        jMenu1.setText("User");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        mnLogin.setText("Login");
        mnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLoginActionPerformed(evt);
            }
        });
        jMenu1.add(mnLogin);

        jMenuItem1.setText("Manage User");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Logout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uts/Barang.png"))); // NOI18N
        jMenu2.setText("Master");

        jMenuItem6.setText("Manage Produk");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uts/Penjualan.png"))); // NOI18N
        jMenu4.setText("Transaksi");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        transaksi.setText("Penjualan");
        transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiActionPerformed(evt);
            }
        });
        jMenu4.add(transaksi);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uts/Laporan.png"))); // NOI18N
        jMenu5.setText("Laporan");

        jMenuItem3.setText("Laporan Penjualan");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         setMenuEnabled(false, "none");  // Menonaktifkan semua menu kecuali Login setelah logout
        JOptionPane.showMessageDialog(this, "Logout berhasil!");
        lblUsername.setVisible(false); 
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        manageUsers manageUsersForm = new manageUsers(username, role); 
        manageUsersForm.setVisible(true);
        manageUsersForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLoginActionPerformed
        // TODO add your handling code here:
       login loginForm = new login(this); // Pass current home to login
    loginForm.setVisible(true);
    loginForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    this.dispose();

    // Mengatur status login setelah form login ditutup
    loginForm.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent windowEvent) {
            if (loginForm.isLoggedIn()) { // Memeriksa status login
                String loggedInRole = loginForm.getRole(); // Ambil role dari login form
                String loggedInUsername = loginForm.getUsername(); // Ambil username dari login form
                
                // Membuka form home dengan username dan role yang sudah login
                home mainMenu = new home(loggedInUsername, loggedInRole); // Pass username dan role ke home
                mainMenu.setVisible(true); // Menampilkan form home
                mainMenu.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                mainMenu.setLoggedIn(true, loggedInRole); // Mengaktifkan status login
                dispose(); // Menutup form login setelah berhasil login
            }
        }
    });
    }//GEN-LAST:event_mnLoginActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiActionPerformed
        // TODO add your handling code here:
        Transaksi TransaksiForm = new Transaksi(username, role);
        TransaksiForm.setVisible(true);
        TransaksiForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_transaksiActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        manageProduk manageProdukForm = new manageProduk(username, role); 
        manageProdukForm.setVisible(true);
        manageProdukForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        LaporanPenjualan LaporanPenjualanForm = new LaporanPenjualan(username, role);
        LaporanPenjualanForm.setVisible(true);
        LaporanPenjualanForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose(); 
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    // Mengatur apakah menu selain login bisa diakses atau tidak
    public void setMenuEnabled(boolean enabled, String role) {
    if (role.equalsIgnoreCase("admin")) {
        // Jika role adalah admin, aktifkan semua menu
        jMenu1.setEnabled(enabled);
        jMenu2.setEnabled(enabled);
        jMenu4.setEnabled(enabled);
        jMenu5.setEnabled(enabled);
        mnLogin.setVisible(false);
        jMenuItem1.setVisible(true); // Tampilkan 'Manage User'
        jMenuItem2.setVisible(true);
        jMenuItem6.setVisible(true); // Tampilkan menu item 6
    } else if (role.equalsIgnoreCase("kasir")) {
        // Jika role adalah kasir, sembunyikan menu tertentu
        jMenu1.setEnabled(enabled);
        jMenu2.setEnabled(false);
        jMenu4.setEnabled(enabled);
        jMenu5.setEnabled(false);
        jMenuItem1.setVisible(false); // Sembunyikan 'Manage User'
        jMenuItem2.setEnabled(enabled);
        jMenuItem2.setVisible(true);
        mnLogin.setVisible(false);
        jMenuItem6.setVisible(false); // Sembunyikan menu item 6
    } else if (role.equalsIgnoreCase("none")) {
        jMenu1.setEnabled(true); // Aktifkan jMenu1 sebelum login
        jMenu2.setEnabled(false);
        jMenu4.setEnabled(false);
        jMenu5.setEnabled(false);
        mnLogin.setVisible(true);  // Tampilkan sub-menu login
        jMenuItem2.setEnabled(false); // Nonaktifkan Logout
        jMenuItem2.setVisible(false); // Sembunyikan menu logout
        jMenuItem1.setVisible(false); // Sembunyikan 'Manage User'
    }
}
    

    // Mengatur status login, jika berhasil login maka menu selain login diaktifkan
    public void setLoggedIn(boolean loggedIn, String role) {
    this.isLoggedIn = loggedIn;
    setMenuEnabled(loggedIn, role);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
        home mainMenu = new home("", ""); // Pass username dan role kosong
        mainMenu.setVisible(true);
        mainMenu.setLoggedIn(false, "none"); // Menonaktifkan semua menu kecuali Login
    }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JMenuItem mnLogin;
    private javax.swing.JMenuItem transaksi;
    // End of variables declaration//GEN-END:variables
}
